---
- name: Download docker images from the docker registry
  hosts: all
  tasks:
    - name: Download docker images
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
        - nginx
        - tomcat
        - httpd
        - ubuntu
        - ghost
...
