---
- name: Create 10 nginx containers for load balancing
  hosts: all
  tasks:
    - name: Create 10 container
      docker_container:
        name: "container{{item}}"
        image: nginx
      with_sequence: count=10
...
