---
- name: Implementing docker compose using ansible playbooks
  hosts: all
  tasks:
    - name: Create mysql container
      docker_container:
        image: mysql
        name: mydb
        env:
          MYSQL_ROOT_PASSWORD: intelliqit


    - name: Create a wordpress container and link with mysql container
      docker_container:
        image: wordpress
        name: mywordpress
        ports:
          - 8888:80
        links:
          - mydb:mysql
...
