---
- name: Create user
  hosts: all
  tasks:
    - name: User creation
      user:
        name: Ramesh
        password: intelliqit
        uid: 9999
        home: /home/Ramesh
        comment: "A normal user"
        shell: /bin/bash
...
