---
- name: Create user on all servers
  hosts: servers

  tasks:
    - name: Create user
      user:
        name: Ravi
        password: intelliqit
        home: /tmp/Ravi
        uid: 1234
        shell: /bin/bash
        comment: "a normal user"
...
