---
- name: Configur tomcat on all servers
  hosts: all
  tasks:
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tocmat10-admin
      apt:
        name: tomcat10-admin
        state: present
    - name: copy customsied tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat frm 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: Pause form 1 min
      pause:
        minutes: 1
    - name: Check tomcat response on server1
      uri:
        url: http://172.31.0.162:9090
        status_code: 200
    - name: Check tomcat response on server2
      uri:
        url: http://172.31.1.133:9090
        status_code: 200
...





