---
- name: Delete if the file is executable uisng when conditions
  hosts: all
  tasks:
    - name: Capture info about the file
      stat:
        path: /tmp/file1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Delete file if it is executable
      file:
        name: /tmp/file1
        state: absent
      when: a.stat.executable == true
...
