---
- name: Install s/w applications
  hosts: all
  tasks:
    - name: Install tree
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - tree
        - maven
        - openjdk-17-jdk
...
