---
- name: Fetch file file from server1
  hosts: 172.31.1.133
  tasks:
    - name: Fetch file
      fetch:
        src: file1
        dest: /tmp
- name: Copy file to server2
  hosts: 172.31.0.162
  tasks:
    - name: Copy file
      copy:
        src: /tmp/172.31.1.133/file1
        dest: /home/ubuntu
...

