---
- name: Change permissions if the file is an empty file
  hosts: all
  tasks:
    - name: Capture file info
      stat:
        path: /tmp/file2
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Change permssions for empty files
      file:
        name: /tmp/file2
        mode: 750
      when: a.stat.size == 0
...
